[variables]
NODE_VERSION = "20.18.1"
PORT = "3102"

[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "npx serve -s frontend/dist -p $PORT --single"
